		.org 0x0000
		rjmp	Reset
		.org 0x0002
		reti
		.org 0x0004
		reti
		.org 0x0008
		reti
		.org 0x000A
		reti
		.org 0x000C
		reti
		.org 0x000E
		reti
		.org 0x0010
		reti
		.org 0x0012
		reti
		.org 0x0014
		reti
		.org 0x0016
		reti
		.org 0x0018
		reti
		.org 0x001A
		reti
		.org 0x001C
		reti
		.org 0x001E
		reti
		.org 0x0020
		reti
		.org 0x0022
		reti
		.org 0x0024
		reti
		.org 0x0026
		reti
		.org 0x0028
		reti

		.org INT_VECTORS_SIZE

